1785/2138: Fixing and Improving Round Report Player Stats
MegaMek/megamek pull request #2780
Opened 2021-04-13 18:22 UTC by Windchild292

This fixes #1785 and fixes #2138 by adding initial unit count tracking, fixing the observer check, and having both change when the one traitors a unit.

2021-04-13 21:18 UTC, NickAragua requested changes
Looks good, got a russian translation for you.

2021-04-13 21:18 UTC, NickAragua commented on megamek/i18n/megamek/common/report-messages_ru.properties
> -7016=<data>: <data> BV осталось (из <data> изначальных) <data> BV убежало
<data>: <data> BV осталось (из <data> изначальных) <data> BV убежало. <data> / <data> бойцов осталось (<data>%).

2021-04-13 21:18 UTC, NickAragua commented on megamek/i18n/megamek/common/report-messages_ru.properties
> -7016=<data>: <data> BV осталось (из <data> изначальных) <data> BV убежало
Can't do a suggestion on deleted lines, but that's a translation.

2021-04-14 01:16 UTC, Windchild292 commented on megamek/i18n/megamek/common/report-messages_ru.properties
> -7016=<data>: <data> BV осталось (из <data> изначальных) <data> BV убежало
Done, thanks for the translation. Merging based on the overall reply.

2021-04-14 01:17 UTC, merged