PL-MASC ToHit mods and Movement mods match IntOps p.84
MegaMek/megamek pull request #3411
Opened 2022-01-27 20:06 UTC by pakfront

for issue 2505

2022-01-27 20:17 UTC, Windchild292 requested changes
Just a few things first

2022-01-27 20:17 UTC, Windchild292 commented on megamek/src/megamek/common/Infantry.java
> +                    && isConventionalInfantry()) {
```suggestion
                && getMovementMode().isLegInfantry()
                && isConventionalInfantry()) {
```

No need for the extra spacing now.

2022-01-27 20:17 UTC, Windchild292 commented on megamek/src/megamek/common/actions/WeaponAttackAction.java
> +                && te.getMovementMode() == EntityMovementMode.INF_LEG
```suggestion
        if ((te instanceof Infantry) && te.hasAbility(OptionsConstants.MD_PL_MASC)
                && te.getMovementMode().isLegInfantry()
```

Our code style uses brackets when it comes to multiple operators.

2022-01-28 01:01 UTC, pakfront commented
Suggs accepted.

2022-01-28 01:03 UTC, Windchild292 approved these changes

2022-01-28 01:03 UTC, merged