Fix landing/takeoff length for small craft and dropships
MegaMek/megamek pull request #3508
Opened 2022-03-10 23:12 UTC by pavelbraginskiy

@NickAragua  Additional fix to the aerodyne hovering fix from earlier. Dropships already override their landing length and will inherit the takeoff length from the small craft class.

2022-03-10 23:31 UTC, pavelbraginskiy commented
I'm still a little unsure on how to interpret the rules on landing/takeoff distance. I've talked to some people and depending on how you interpret it, the short landing might just be limited to fighters but the short takeoff might be usable by small craft/dropships since those count as VSTOL. But it wasn't that way in megamek before, so I'm unsure.

2022-03-10 23:40 UTC, pavelbraginskiy commented
![image](https://user-images.githubusercontent.com/29113974/157773745-fca0efc4-79d9-4824-bd03-31cfc922f7b8.png)
![image](https://user-images.githubusercontent.com/29113974/157773792-d394c1c2-6d99-4c25-80a5-bbf8fdb3d4c5.png)
Some of the ongoing discussion on the subject

2022-03-11 18:31 UTC, NickAragua commented
@HammerGS may be able to weigh in on the rules aspect of this.

2022-10-28 16:17 UTC, SJuliez commented
From the rules, I think I agree with the landing length of 8 for SC but not with the takeoff length of 20. According to TM p188 aerodyne SC have VSTOL. According to TW p88 VSTOL-equipped units lift off in 10.

2022-10-28 16:19 UTC, SJuliez requested changes

2022-12-28 22:16 UTC, SJuliez commented
Replaced by #4077

2022-12-28 22:16 UTC, closed without merging