Darken icons on the minimap for moved units
MegaMek/megamek pull request #3733
Opened 2022-06-24 21:09 UTC by mangofeet

2022-06-24 21:18 UTC, Windchild292 approved these changes

2022-06-24 21:26 UTC, mangofeet commented
There are some color blindness issues in the Green-Blind/Deuteranopia and Monochromacy/Achromatopsia categories that I should sort out before this is merged

2022-06-24 23:24 UTC, Windchild292 requested changes
Just one spacing issue, which should probably be a float too

2022-06-24 23:24 UTC, Windchild292 commented on megamek/src/megamek/client/ui/swing/minimap/Minimap.java
> +            g2.setStroke(new BasicStroke(innerBorderWidth/2, BasicStroke.CAP_BUTT, BasicStroke.JOIN_MITER));
```suggestion
            g2.setStroke(new BasicStroke(innerBorderWidth / 2f, BasicStroke.CAP_BUTT, BasicStroke.JOIN_MITER));
```

2022-06-25 16:43 UTC, Windchild292 approved these changes
Looks good, thanks for the PR

2022-06-25 16:59 UTC, merged