Correctly load damaged CI from MUL
MegaMek/megamek pull request #3925
Opened 2022-10-09 11:57 UTC by SJuliez

Applies a reduced trooper count from a .MUL to both the "men" and "shootingMen" fields so that the CI really knows how strong it is (when loading a damaged CI and then choosing "edit damage" in the lobby, this would show the wrong value.)

2022-10-10 21:18 UTC, neoancient requested changes

2022-10-10 21:18 UTC, neoancient commented on megamek/src/megamek/common/MULParser.java
> +                    if (entity.isConventionalInfantry()) {
This needs to happen for BattleArmor also.

2022-10-11 09:05 UTC, SJuliez commented
OK for BA internal damaged = destroyed and the applydamage needs to happen at another place in the MUL Parser. But I've used the instanceof check in all places to make it happen for both BA and CI. I also added a change to the lobby damage editor dialog so that lobby damage arrives correctly.

2022-10-12 00:07 UTC, neoancient approved these changes

2022-10-12 16:58 UTC, merged