#3949 RFE: Unit Display more enhancements implement
MegaMek/megamek pull request #3950
Opened 2022-10-29 14:04 UTC by kuronekochomusuke

#3949 RFE: Unit Display more enhancements 

- add ability to set the panel order for the nontabbed version in the Client Settings
- save the size and position of the tabbed and nontabbed version independently

2022-11-01 19:36 UTC, kuronekochomusuke commented
This is ready for review

2022-11-02 16:25 UTC, NickAragua requested changes
Looks fine, just needs a few long term maintainability tweaks.

2022-11-02 16:25 UTC, NickAragua commented on megamek/src/megamek/client/ui/swing/CommonSettingsDialog.java
> +            if ((s > 0) && (!unitDisplayNonTabbed.get(0).equals(UnitDisplayOrderPreferences.getInstance().getString("NonTabbedA1")))) {
I'm seeing a lot of repeated magic numbers (s > 0, .get(0)) and magic strings (e.g. "NonTabbedA1") here, can we put them into enums or constants instead? It'll make this easier to maintain going forward.

2022-11-03 13:24 UTC, NickAragua approved these changes
Good to go.

2022-11-03 13:25 UTC, merged