RFE 426 overlay for Planetary Conditions
MegaMek/megamek pull request #3969
Opened 2022-11-07 23:38 UTC by kuronekochomusuke

RFE #3820 426 overlay for Planetary Conditions

cloned the KeyBindingsOverlay to display Planetary Conditions

Are there any other conditions that would be good to add to this?

2022-11-08 16:39 UTC, SJuliez commented
Also: I remember that people had difficulty with this initially because the keybind didn't work properly. iirc you'd have to add the keybind default to the keybinds.xml file that is somewhere in the config folder.

2022-11-08 16:40 UTC, SJuliez commented
Thirdly :) you might wanna make sure that it doesnt show up in the board editor.

2022-11-08 17:35 UTC, kuronekochomusuke commented
- colors can be set in advance options
- added condition indicators
- change temperature color based on extreme temperature ranges
- align to right side

![image](https://user-images.githubusercontent.com/116095479/200635234-f78a250f-3959-4810-9428-b7059dbf0457.png)

2022-11-08 18:28 UTC, SJuliez commented
> Also: I remember that people had difficulty with this initially because the keybind didn't work properly. iirc you'd have to add the keybind default to the keybinds.xml file that is somewhere in the config folder.

Sorry if I was not making sense: I was speaking of the key bind overlay. But the same is true for the new overlay.

2022-11-08 18:31 UTC, kuronekochomusuke commented
I tried updating the keybinds.xml for  this and added in null checks for the  board editor

2022-11-08 20:35 UTC, kuronekochomusuke commented
- add advance option to hide default conditions

2022-11-10 22:37 UTC, kuronekochomusuke commented
- scale overlay based on the GUI scale

![image](https://user-images.githubusercontent.com/116095479/201220756-4d694239-f1bc-45b5-95a1-3b343b45bf44.png)

![image](https://user-images.githubusercontent.com/116095479/201220649-176b4a7e-3ba5-47e1-877c-c8d767f67722.png)

2022-11-10 22:41 UTC, HammerGS commented
Looking good!

2022-11-11 15:41 UTC, kuronekochomusuke commented
- add advance setting to show the header, labels, values, and indicators

![image](https://user-images.githubusercontent.com/116095479/201374560-ce5ed630-e5ca-4e61-b4e5-ba6a5d1f69fa.png)

![indicatorScreenshot 2022-11-11 101335](https://user-images.githubusercontent.com/116095479/201372676-8b0d9ad8-85ce-4da5-a130-e26027a78658.png)

2022-11-17 20:01 UTC, kuronekochomusuke commented
This is now ready for review

2022-12-14 21:04 UTC, SJuliez requested changes
I like this a lot! Just one small request then I'll merge it.

2022-12-14 21:04 UTC, SJuliez commented on megamek/src/megamek/client/ui/swing/boardview/PlanetaryConditionsOverlay.java
> +        if (e.getName().equals(KeyBindParser.KEYBINDS_CHANGED)) {
I believe it's not hurtful to just set changed to true here without doing any checks (PreferenceChangeEvents don't happen all the time); this way it'll react to changes to its advanced settings.

2022-12-14 22:31 UTC, SJuliez approved these changes

2022-12-15 22:18 UTC, merged