RFE add search functionality to the mini report dialog
MegaMek/megamek pull request #4004
Opened 2022-11-24 19:42 UTC by kuronekochomusuke

RFE #4003 add search functionality to the mini report dialog

search through the currently selected report tab based on the chosen options

search by players
search by owned units
search by keyword

![image](https://user-images.githubusercontent.com/116095479/203855237-0caa0dd1-659a-458e-9478-5b6bfaff4342.png)

![image](https://user-images.githubusercontent.com/116095479/203855349-b1bdc488-1ae8-4b48-995d-e440a38c8779.png)

2022-11-25 15:12 UTC, HammerGS commented
I think this has a lot of possibilities and will play around with it this weekend.

2022-11-26 02:56 UTC, NickAragua requested changes
Needs a little less home-grown O(n*m) text search algorithm, but good idea otherwise.

2022-11-26 02:56 UTC, NickAragua commented on megamek/src/megamek/client/ui/swing/util/UIUtil.java
> +            String match = text.substring(currentPos, currentPos + searchPattern.length());
Can't you just replace this whole thing with text.indexOf(searchPattern, startindex)? I'm all for rolling your own algorithms, but this is a solved problem, and I don't think we need a home-grown O(n*m) solution here.

2022-11-26 02:56 UTC, NickAragua commented on megamek/src/megamek/client/ui/swing/util/UIUtil.java
> +            String match = text.substring(currentPos, currentPos + searchPattern.length());
Searching backwards can be accomplished by using lastIndexOf(searchPattern, startIndex)

2022-11-27 16:46 UTC, kuronekochomusuke commented
added the hyperlink support

2022-11-27 22:55 UTC, NickAragua approved these changes

2022-11-28 15:57 UTC, merged