show game board in all the game phases
MegaMek/megamek pull request #4030
Opened 2022-12-09 23:46 UTC by kuronekochomusuke

show game board in all the game phases

#2193

- convert the report display to be based off of the StatusBarPhaseDisplay to show the game board in all of the phases.   
- remove the report display from the main gui and use the mini report dialog to view the phase reports.
- add buttons to the report phases to show the mini report dialog and the player list dialog.   
- when entering the report phases show the mini report dialog.

![image](https://user-images.githubusercontent.com/116095479/206812686-96a0e543-d6ab-4f46-b2bc-9ec21cde772e.png)

2022-12-10 19:25 UTC, HammerGS commented
Just starting to play around and look at this. I'll let you know anything I find, but very cool so far.

2022-12-11 00:05 UTC, HammerGS commented
Played a longish game today. It the more I used it the more I found myself constantly moving windows around. Is this something that could be dockable?

2022-12-11 00:27 UTC, kuronekochomusuke commented
which windows were an issue?

do you know if there is some library that implements docking panels?

2022-12-11 18:56 UTC, HammerGS commented
Sorry for the delay. I found the Player list in particular always seemed to be in the way and I found I closed it everytime it appeared.  Only to have it reopen depending on the phase. I'm prone to changing the size of the main window depending on the turn which I think is part of the issue. 

I seem to recall testing this when mjog was developing it and the docking part worked in conjunction with  https://github.com/MegaMek/megamek/pull/3125https://github.com/MegaMek/megamek/pull/3125.  Which had great player feedback other than then bug of it constantly growing in size. 

I really love the report being available and for me, is a game changer in how the program is played. Which as led me to some thoughts on your report filter (which I'll open as a separate RFE). 

I feel like if it remembered positions and what was opened and closed it would be perfect, or the dream dock able.

2022-12-12 00:54 UTC, kuronekochomusuke commented
you can turn off the player list  or report auto popup by unchecking them in the menu.   they currently auto popup on the reporting phases if checked.  the unit display and mini map auto popup on non-report phases if checked.

was thinking it maybe good to have a setting for the auto popups by phase, instead of using the check marks.   so you could set to show, hide, or manual for each phase for the unit display, mini map, report display, and the player list.     that way you could set them to display or hide how you liked.   the check mark system does not give you much flexibly in how it works.  

I think some of the unit display growing in  size may have been fixed in the tab and non-tabbed unit display pull request.   I was running it to some of that with it.   I fixed some things in the pilot and armor tab then.    

would yall like to try to make it dock with this pull request or in a new one?      was think to make make the report display and the unit display dockable, or just one to start to see if it works.  would try to do it like the Lounge -> Team Overview

2022-12-12 22:15 UTC, kuronekochomusuke commented
added Auto Display setting to control when the Unit Display, Minimap, Round Report, and Player List are automatically shown.  Can set them to be shown, hidden, or controlled manually on Report Phases and Non-Report Phases.  

Allowing it to be set for every phase makes it too complicated, so i went with just  Report Phases and Non-Report Phases.  

![image](https://user-images.githubusercontent.com/116095479/207165486-9cb9cf70-4a5c-4474-aaa5-e270e6d058c7.png)

2022-12-24 01:01 UTC, kuronekochomusuke commented
- added "docking" for the unit display.  
- can "switch location" between window mode, left side of board and right side of board.
- will add mini report if this works fine.

![image](https://user-images.githubusercontent.com/116095479/209416164-14933fdb-f8ae-4568-b99b-e6e4aee2ea25.png)

still working thru stuff, but good enough to see how it works.

2022-12-24 18:11 UTC, kuronekochomusuke commented
- added in "docking" for the mini report display
- can "switch location" between window mode, left side of board and right side of board.

![image](https://user-images.githubusercontent.com/116095479/209447049-63975008-26c8-47fb-8bd0-d59c147d4dba.png)

2022-12-26 02:35 UTC, kuronekochomusuke commented
- had to make the "docking" on left and right side of the board an advanced setting.  
- defaults to docking on the left
- Could not get it to remember the split pane positions correctly when one was docked on the left and the other docked on the right.

2022-12-26 15:36 UTC, kuronekochomusuke commented
- add an advance setting to allow switching the between stacking multiple panels on the y axis or x axis
- defaults to y axis
- x axis setting is probably only usable if you have an wide screen monitor.

here is when it is set to x axis, the previous screenshot shows the y axis behavior.
![image](https://user-images.githubusercontent.com/116095479/209564009-0c2fc8ea-3c02-4fae-b724-3ac4d04b4464.png)

2022-12-27 19:54 UTC, kuronekochomusuke commented
this is ready for review now

2022-12-27 19:58 UTC, HammerGS commented
I was playing with this morning and so far it's really cool. It struck me with the changes that I kept going to View to look for the round report. Would it make sense more the round report from the Game menu to the View menu? Maybe in the same area as the unit display?

2022-12-27 20:00 UTC, kuronekochomusuke commented
can move it over there.  move the player list also?  it fits with those also

2022-12-27 20:02 UTC, HammerGS commented
> can move it over there. move the player list also? it fits with those also

yeah, I think that makes sense, to me when you close it you want to "view" it again.

2022-12-27 20:24 UTC, kuronekochomusuke commented
grouped the dialogs and overlays together in the view menu and moved them up some.

![image](https://user-images.githubusercontent.com/116095479/209718137-c1c1dc11-f066-46b1-996f-fa7617f1db13.png)

2022-12-27 20:30 UTC, HammerGS commented
> grouped the dialogs and overlays together in the view menu and moved them up some.
> 
> ![image](https://user-images.githubusercontent.com/116095479/209718137-c1c1dc11-f066-46b1-996f-fa7617f1db13.png)

I think that flow makes much more sense.

2022-12-27 20:32 UTC, kuronekochomusuke commented
add a divider between dialogs and overlays

![image](https://user-images.githubusercontent.com/116095479/209719403-434af2c2-bcbb-42dc-9f35-ea1e7b097744.png)

2023-01-10 10:30 UTC, SJuliez requested changes
Tested it and liked it a lot. I have a few comments on the code.

2023-01-10 10:30 UTC, SJuliez commented on megamek/src/megamek/client/ui/dialogs/UnitDisplayDialog.java
> +        if ((this.getSize().width * this.getSize().height) > 0) {
It seems the "this." can be removed here

2023-01-10 10:30 UTC, SJuliez commented on megamek/src/megamek/client/ui/dialogs/UnitDisplayDialog.java
> +            savePref();
As in the previous file: Could the savePref() call be moved up to the WindowClosing listener?

2023-01-10 10:30 UTC, SJuliez commented on megamek/src/megamek/client/ui/dialogs/MiniReportDisplayDialog.java
> +        if ((e.getID() == WindowEvent.WINDOW_DEACTIVATED) || (e.getID() == WindowEvent.WINDOW_CLOSING)) {
Could the savePref() be moved up to the WindowClosing listener with the same result?

2023-01-10 10:30 UTC, SJuliez commented on megamek/src/megamek/client/ui/swing/ClientGUI.java
> +            String action = GUIP.getMinimapAutoDisplayReportPhase();
This confuses me. Shouldn't a GUIP call return a boolean for something like this?

2023-01-10 10:30 UTC, SJuliez commented on megamek/src/megamek/client/ui/swing/GUIPreferences.java
> +    public static final String PLAYER_lIST_POS_X = "PlayerListPosX";
There is a non-capital L in the next few names

2023-01-10 10:30 UTC, SJuliez commented on megamek/src/megamek/client/ui/swing/GUIPreferences.java
> +        store.setDefault(MINI_REPORT_AUTO_DISPLAY_REPORT_PHASE, MSG_SHOW);
Repeated from above: This should be boolean values, unless there is a reason against that that Im not seeing. At the very least it shouldnt be localized strings.

2023-01-10 10:30 UTC, SJuliez commented on megamek/src/megamek/client/ui/swing/PlayerListDialog.java
> +    private static final String MSG_TITLE = Messages.getString("PlayerListDialog.title");
You removed many of those static final localized strings in the other PR :) just saying, I don't mind

2023-01-10 10:30 UTC, SJuliez commented on megamek/src/megamek/client/ui/swing/PlayerListDialog.java
> +    private boolean model;
model?

2023-01-10 10:32 UTC, SJuliez commented on megamek/src/megamek/client/ui/swing/PlayerListDialog.java
> +    private static final String MSG_TITLE = Messages.getString("PlayerListDialog.title");
There is no need to change this, I just noticed it.

2023-01-12 20:08 UTC, SJuliez approved these changes

2023-01-13 20:19 UTC, merged