Issue 2695: Remove newlines from GameOptions tooltips
MegaMek/megamek pull request #4038
Opened 2022-12-12 22:33 UTC by SJuliez

Partly solves issue #2695.

This removes most of the strangely placed newlines from the GameOptions tooltips and uses a sensible fixed width to make the tooltips break automatically.

![image](https://user-images.githubusercontent.com/17069663/207169278-0a57183b-ea8c-4b12-bb4c-8c9760cbc9d3.png)

instead of

![image](https://user-images.githubusercontent.com/59574316/110187858-da668000-7de7-11eb-96df-5ab9a7006ed2.png)

2022-12-13 02:04 UTC, Windchild292 requested changes
This replaces single spaced separations with double spaced separations, which is an accessibility issue. I've commented on four cases with problems before determining that's common in this PR.

2022-12-13 02:04 UTC, Windchild292 commented on megamek/i18n/megamek/common/options/messages.properties
> +GameOptionsInfo.option.no_forced_primary_targets.description=If selected the Total Warfare rules on page 109that require the primary target to be in the front arc are ignored
```suggestion
GameOptionsInfo.option.no_forced_primary_targets.description=If selected the Total Warfare rules on page 109 that require the primary target to be in the front arc are ignored
```

2022-12-13 02:04 UTC, Windchild292 commented on megamek/i18n/megamek/common/options/messages.properties
> +GameOptionsInfo.option.individual_initiative.description=If checked, each unit has its own initiative roll, and must move in that fixed order.  Good for zellbrigen or RPG style games. Incompatible wi
```suggestion
GameOptionsInfo.option.individual_initiative.description=If checked, each unit has its own initiative roll, and must move in that fixed order. Good for zellbrigen or RPG style games. Incompatible with the lance movement options.
```

2022-12-13 02:04 UTC, Windchild292 commented on megamek/i18n/megamek/common/options/messages.properties
> +GameOptionsInfo.option.initiative_streak_compensation.description=If checked, awards an increasing initiative roll bonus to a team that loses initiative several times in a row.  Incompatible with Ind
```suggestion
GameOptionsInfo.option.initiative_streak_compensation.description=If checked, awards an increasing initiative roll bonus to a team that loses initiative several times in a row. Incompatible with Individual Initiative.
```

2022-12-13 02:04 UTC, Windchild292 commented on megamek/i18n/megamek/common/options/messages.properties
> +GameOptionsInfo.option.protos_move_multi.description=If checked, multiple ProtoMechs will have to move in place of a single Mek or Vehicle. Set the number per mech in the appropriate Game Option.  If
```suggestion
GameOptionsInfo.option.protos_move_multi.description=If checked, multiple ProtoMeks will have to move in place of a single Mek or Vehicle. Set the number per Mek in the appropriate Game Option. If there are less than above specified protos remaining, they all must move. The move order includes the presence of ProtoMeks. Mutually exclusive with "ProtoMeks move after Meks and Vehicles". Unchecked by default.
```

2022-12-13 22:34 UTC, SJuliez commented
Ok double spaces should be resolved. Also went through it all and replaced mech with Mek (also in Protomech and mechwarriors).

2022-12-16 16:16 UTC, Windchild292 approved these changes

2022-12-16 22:30 UTC, merged