add filters tech level and tech base
MegaMek/megamek pull request #4207
Opened 2023-02-25 19:04 UTC by kuronekochomusuke

- add filter tech level 
- add filter tech base

![image](https://user-images.githubusercontent.com/116095479/221375026-3b0aa7c1-5e7a-4200-be53-2972b39a2249.png)

2023-02-26 04:43 UTC, HammerGS approved these changes
Testing this and works fine.

2023-02-26 09:06 UTC, SJuliez commented
Just curious: Do these two fields lead to different results from the fields we have in the unit selector main window?

2023-02-26 11:34 UTC, kuronekochomusuke commented
yes, it is different.   The new Tech Level and Tech Base come from the values set in MegaMekLab and are shown on the summary tab of the mech preview in the add a combat unit search.  

Not sure where the Type: in the add a combat unit search comes from.

2023-02-26 12:20 UTC, kuronekochomusuke commented
would think the tech level should be the same, but they are not.  

could be these are old files that need to be updated, to have the tech level set correctly.

Type: unofficial
![image](https://user-images.githubusercontent.com/116095479/221409921-c8830ea6-46d0-4ef1-9bcd-a99e976a5596.png)

Tech Level: unofficial
![image](https://user-images.githubusercontent.com/116095479/221409967-c164ceee-896e-4e72-8460-14c476996cba.png)

2023-02-27 22:24 UTC, SJuliez requested changes

2023-02-27 22:24 UTC, SJuliez commented on megamek/src/megamek/client/ui/swing/unitSelector/TWAdvancedSearchPanel.java
> +        loadTriStateItem(SimpleTechLevel.getDescriptions(), listTechLevel, 5);
I have noticed in a previous PR but didn't comment on it. Would you mind adding a version of this that ccepts a List<String>. Lists are generally preferable to arrays for safety and general ease of handling and well, modernity. Generating that list im SimpleTechLevel is at least one method call shorter then. The getEngineTypes method would also be simpler.

2023-02-27 22:25 UTC, SJuliez commented on megamek/src/megamek/client/ui/swing/unitSelector/TWAdvancedSearchPanel.java
> +        loadTriStateItem(SimpleTechLevel.getDescriptions(), listTechLevel, 5);
a `List<String>`
the formatting swallowed that :)

2023-02-28 10:20 UTC, SJuliez approved these changes

2023-02-28 10:22 UTC, merged