correct issue with missing background transparency for key bind overlay
MegaMek/megamek pull request #4351
Opened 2023-04-23 14:04 UTC by kuronekochomusuke

- correct issue with missing background transparency for key bind overlay
 this was caused in PR #4313

should the background transparency be a client setting for the key bind and Planetary Conditions overlays?

2023-04-23 14:55 UTC, HammerGS commented
It makes sense to me.

2023-04-26 02:41 UTC, NickAragua requested changes
Looks fine, let's see if we can use existing controls for user input validation.

2023-04-26 02:41 UTC, NickAragua commented on megamek/src/megamek/client/ui/swing/CommonSettingsDialog.java
> +        planetaryConditionsBackgroundTransparency.setText(String.format("%d", GUIP.getPlanetaryConditionsBackgroundTransparency()));
Isn't there an input control that's like a number spinner or something that ensures the user is limited to entering numbers? JSpinner?

2023-04-27 02:46 UTC, NickAragua approved these changes

2023-04-27 02:46 UTC, merged