add client setting for Max Range to Draw Sensor / Visual Rings
MegaMek/megamek pull request #4470
Opened 2023-05-29 20:59 UTC by kuronekochomusuke

- add client setting for Max Range to Draw Sensor / Visual Rings
- to help with lag in the case when sensor range is 1000+

![image](https://github.com/MegaMek/megamek/assets/116095479/4f705a6d-b457-4e00-b73c-66cb98ad3633)

fixes #4467

2023-05-30 01:48 UTC, NickAragua requested changes
Spelling fix. Also, discussion point: do we really need the extra setting? Why not just cap the draw range to the bigger of board width/height and call it a day? I don't think I've ever seen a board bigger than 200x200.

2023-05-30 01:48 UTC, NickAragua commented on megamek/src/megamek/client/ui/swing/boardview/BoardView.java
> +            int rangeMin = Math.min(rangeH.min, GUIP.getSenorMaxDrawRange());
"Senor" Max Draw Range?

2023-05-30 13:12 UTC, kuronekochomusuke commented
would just capping still lag people with slow computers on large maps?  the setting allows it be be dialed back to what your computer can handle.

2023-05-30 14:33 UTC, kuronekochomusuke commented
it calculates out to max range, then removes them any not on the board, before it tries to draw anything.   it grows larger the further out you are, since it adds a other circle of points each step.  

I have added logic to only calculate out to max range from your position on the board, that should help.

2023-05-31 20:19 UTC, SJuliez commented
I'd like to second @NickAragua suggestion to not give this a client setting if it can be avoided. The algorithm for determining the hexes to paint can be improved a lot here I think. If I'm not mistaken, the thing to draw here is a ring of hexes at the respective range, right? So the only hexes that can possibly have a sprite are those at exactly the range and those on the board edge. Those on the board edge could be omitted because that doesn't add any relevant information (obviously, any range ends at the board edge). First, check if X > board diagonal. If so, draw nothing. Otherwise, add those at range X, not all those from range 0 to X. Then remove any not on the board. Then to determine the edges to draw just compare the surrounding hexes if they're more distant than X. Unless range X = 0, only a maximum of 3 edges can ever be there. This should speed up things and I'm sure there is more potential improvement. I hope I made not too many errors in this.

2023-05-31 21:17 UTC, kuronekochomusuke commented
with sensors currently, the start is drawn on the near side of the hex, and the end is on the far edge.  this helps showing they are one range.  not sure your algorithm would handle that.    

also drawing the ones along the board edge help show that the two ranges are connected and the sensors are active between the two.  

drawing along the board edge shows that you can see up to that edge.

2023-05-31 21:52 UTC, NickAragua approved these changes
It's a major improvement over what was there before anyway. If the person reporting the issue is still experiencing slowness afterwards, then we can work on further improvements in the spirit of those outlined by @SJuliez, in terms of not looping through every hex on the map.

2023-05-31 21:54 UTC, kuronekochomusuke commented
also if you turn it off, nothing will calculate now.

2023-06-07 13:25 UTC, merged