Feature - Add audio tab and master volume setting
MegaMek/megamek pull request #4661
Opened 2023-07-23 02:49 UTC by sensualcoder

This PR adds a Master Volume setting to the application to control the sound output, and also moves the audio settings into a new tab in the Client Settings menu.

In addition, there is a new Sound class that encapsulated storing and playing sound files, and a SoundManager class to provide an interface for all of the current sounds effects as well as handling audio settings changes.

2023-07-23 02:54 UTC, HammerGS commented
Thanks for the PR. We are getting close to the 0.49.14 Dev release, so this will get tagged with a "For new dev cycle (49.15).

If you haven't joined our Discord I'd recommend joining it as its an easy way to get feedback.

2023-07-23 04:39 UTC, NickAragua approved these changes

2023-08-02 17:12 UTC, sensualcoder commented
Updated this PR with some small changes

2023-08-07 01:47 UTC, NickAragua requested changes
Looks good, I'd like to see a few comments on some the new classes.

2023-08-07 01:47 UTC, NickAragua commented on megamek/src/megamek/client/ui/swing/audio/Sound.java
> +public class Sound
Can we get some comments in this class describing what it does?

2023-08-08 04:29 UTC, sensualcoder commented
Added some comments explaining the Sound class and methods and the methods in SoundManager. Let me know if I should add more :)

2023-08-08 14:28 UTC, merged