MekView updates
MegaMek/megamek pull request #4822
Opened 2023-10-11 16:06 UTC by SJuliez

Some updates to the unit summary:

- adds a toolbar like on the AS Card that allows font configuration and copying the info as text or html
- removes some background coloring that wasnt compatible with dark look and feel, now damage is colored in the configurable warning color aka red and caution color aka yellow
- scrolling should be smoother (smaller increment)
- the tables (armor, weapons etc) now have a little space between columns, most columns are centered
- unnecessary empty lines between text blocks have been removed
- html tags in the fluff text are removed for text export, so simple html tags like `<P>, <BR>, <B> and <I>` can be used to add line breaks and formatting
- the MUL link from the "Source:" text has been removed, there's now a button
- instead, when the source is Shrapnel, a link to the Shrapnel website on bg.battletech.com is present
- in the lobby, the summary scales correctly according to GUI scaling (override on SetVisible)

![image](https://github.com/MegaMek/megamek/assets/17069663/f8f916b3-36b8-4a0b-84da-0b69e8eb8108)

2023-10-11 20:33 UTC, rjhancock approved these changes
Sanity check looked fine to me.

2023-10-12 14:34 UTC, NickAragua requested changes
One question, one minor change request.

2023-10-12 14:34 UTC, NickAragua commented on megamek/src/megamek/common/MechView.java
> +            if (source.contains("Shrapnel")) {
Also, not sure if we really want a magic string here.

2023-10-12 14:34 UTC, NickAragua commented on megamek/src/megamek/common/MechView.java
> +            String htmlCleanedText = value.replaceAll("<[Bb][Rr]> *", "\n")
Is that really all the html tags that can show up in this text?

2023-10-12 21:00 UTC, SJuliez commented on megamek/src/megamek/common/MechView.java
> +            if (source.contains("Shrapnel")) {
Well the source is just a text in the unit files. If it says "shrapnel" or "Shranpel" then it's misspelled and waiting for correction :). This feels like something for the canon units, not player constructed. I'm not against using toLowerCase. Just doesn't look like it needs versatility.
On magic string: What do you suggest? make it a constant?

![image](https://github.com/MegaMek/megamek/assets/17069663/68a6eac7-77f3-4fe6-832f-67860dca4fc9)

2023-10-12 21:27 UTC, HammerGS commented on megamek/src/megamek/common/MechView.java
> +            if (source.contains("Shrapnel")) {
If we had a list of the products (like from MUL) could we have them in a separate file to manage? I think I have one.

2023-10-13 00:56 UTC, NickAragua commented on megamek/src/megamek/common/MechView.java
> +            if (source.contains("Shrapnel")) {
Yeah, I think a constant will do for now.

2023-10-13 00:57 UTC, NickAragua commented on megamek/src/megamek/common/MechView.java
> +            String htmlCleanedText = value.replaceAll("<[Bb][Rr]> *", "\n")
Ok for now. If we wind up having html elements that aren't getting caught then we can look into a more robust solution.

2023-10-17 01:05 UTC, NickAragua approved these changes

2023-10-18 15:28 UTC, merged