add deployment options
MegaMek/megamek pull request #4922
Opened 2023-11-24 16:39 UTC by kuronekochomusuke

- add option to default Non-bot players to team 1
- add option for Non-bot player entities with \"Use Owners*\" deployment set, use Player 0\'s settings, instead of current player\'s settings
- these should help speed up lobby setup in coop games.
- defaulted them to off, to have the current behavior.

![image](https://github.com/MegaMek/megamek/assets/116095479/cc7a47a9-b81b-4f79-84b5-b48332538ece)

![image](https://github.com/MegaMek/megamek/assets/116095479/0428d6ea-7285-4d65-8c5f-55e5f9a15c8a)

2023-11-24 18:10 UTC, HammerGS commented
This sounds like a huge help for games like Joker runs.

2023-12-19 22:40 UTC, SJuliez requested changes
I'd appreciate if the texts could be adjusted but otherwise good to go. I wonder if we might once upgrade deployment to a class that supports various forms of deployment areas. This might lighten the load of specialized code such as the one in here for Entity, PlayerSettings and other classes and offer more variety of deployment. I once went through some of the Chaos Campaign books and noted all deployment variations. Quite a lot of different area types. Also, it could be interesting to have deployment options that can be programmed in MHQ but are difficult to represent in a GUI.

2023-12-19 22:40 UTC, SJuliez commented on megamek/i18n/megamek/client/messages.properties
> +BoardSelectionDialog.ViewGameBoardButton=refresh preview
Since this is a button text I feel this needs at least a capital letter as the first

2023-12-19 22:40 UTC, SJuliez commented on megamek/i18n/megamek/client/messages.properties
> +CustomMechDialog.BtnDeploymentUseRulerTip=set the Any NW and SE corners based on the corners of the NW and SE corners the square defined by the map preview ruler
Capital letter

2023-12-19 22:40 UTC, SJuliez commented on megamek/i18n/megamek/common/options/messages.properties
> +GameOptionsInfo.option.set_default_team_1.description=Unchecked each player is assigned new team
I feel this is not understandable unless you already know what it does. At least it should start with "When this option is unchecked, "

2023-12-19 22:40 UTC, SJuliez commented on megamek/i18n/megamek/common/options/messages.properties
> +GameOptionsInfo.option.set_player_deployment_to_player0.description=Unchecked use current player deployments settings
ditto

2023-12-19 22:49 UTC, sldfgunslinger2766 commented
As per Julie's comment on the Chaos Campaign deployment types: being able to deploy on more than one 'edge/side' would be really useful and cool...

2023-12-20 18:54 UTC, SJuliez approved these changes

2023-12-21 16:43 UTC, merged