add in game force display dialog
MegaMek/megamek pull request #4985
Opened 2023-12-30 20:51 UTC by kuronekochomusuke

- add in game force display dialog, similar to the lobby force display 
- double clicking a unit views it in unit display and centers unit on game board

![image](https://github.com/MegaMek/megamek/assets/116095479/6ed069e3-4dee-4012-a201-a4da6de68036)

2024-01-06 03:43 UTC, HammerGS commented
Been playing around with this, very cool feature and have found no issues with it. But testing has been limited a smaller scale.

2024-01-11 21:33 UTC, HammerGS commented
Wanted to confirm if this is still in development or ready to go?

2024-01-11 22:37 UTC, kuronekochomusuke commented
this is ready to review

2024-01-15 09:40 UTC, Sleet01 requested changes
Just a couple of minor typos, otherwise looks good.

2024-01-15 09:40 UTC, Sleet01 commented on megamek/src/megamek/client/ui/swing/GUIPreferences.java
> +    public static final String FORCE_DISPLAY_AUTO_DISPLAY_NONREPORT_PHASE = "ForceDisplayAutoDiplayNonReportPhase";
Typo: `ForceDisplayAutoDiplay` -> `ForceDisplayAutoDisplay`

2024-01-15 15:47 UTC, merged