Don't display engine rating for SV engines
MegaMek/megamek pull request #4992
Opened 2024-01-01 08:07 UTC by SJuliez

Removes the engine rating (but not the engine type) from the mech summary and the record sheet for support vehicles as they don't use engine ratings.

old:
![image](https://github.com/MegaMek/megamek/assets/17069663/c77b3dfe-f69e-4e9f-8d10-fee4cad46dec)

new:
![image](https://github.com/MegaMek/megamek/assets/17069663/1e6391e9-55e9-4379-a224-3f277adabb09)

2024-01-02 22:42 UTC, neoancient requested changes

2024-01-02 22:42 UTC, neoancient commented on megamek/src/megamek/common/Engine.java
> +                return String.format("%s", Messages.getString("Engine." + TYPE_KEYS[engineType])).trim();
No need to call String.format.
```suggestion
                return Messages.getString("Engine." + TYPE_KEYS[engineType]).trim();
```

2024-01-03 05:14 UTC, HammerGS commented
Errata issued by CGL that could provide a better option. 

https://bg.battletech.com/forums/index.php/topic,27319.msg1984570.html#msg1984570

2024-01-03 19:33 UTC, neoancient approved these changes

2024-01-03 19:35 UTC, neoancient commented
We could change it to show the effective rating for the stackpole rule, but that's easily calculated from the information on the sheet and it only applies to fusion engines. I think it would be fine to leave it off.

2024-01-04 16:03 UTC, HammerGS commented
It was originally a CGL request to add the number. They created the errata specifically to show the rating for SV's. So we should go ahead and show the new errata value and engine type for them.

2024-01-09 17:00 UTC, merged