Fix aerospace attack values for LBX autocannons
MegaMek/megamek pull request #5565
Opened 2024-06-11 20:55 UTC by neoancient

The AV for LBX autocannons (other than the LB2X) are incorrect. See TW, pp. 303-4.

2024-06-11 20:59 UTC, IllianiCBT approved these changes
LGTM

2024-06-11 22:28 UTC, gsparks3 commented
I seem to recall this previously causing issues with aerospace units not doing the correct amount of damage with LBX autocannons. [LBXHandler.java](https://github.com/MegaMek/megamek/blob/89685d1ccab4b6586590f9f836475eec4e456910/megamek/src/megamek/common/weapons/LBXHandler.java#L67) in particular contains code (lines 67-74) that will reduce LBX attack values to 60% of their specified value. If it is preferred to have the correct values in the weapon definition files, removing that code might be best. Either way, this could use testing to confirm that aerospace units are doing the expected amount of damage with LBX autocannons after the changes.

2024-06-13 22:41 UTC, gsparks3 commented
Tested the Gradle artifact for the PR; I can now confirm that this causes LBX autocannons to do less damage than intended. Does seem to be following the `Math.floor(0.6 * av)` behavior from that bit of code in LBXHandler.java (6 * 0.6 = 3.6, floor to 3 for LBX10, 12 *0.6 = 7.2, floor to 7 for LBX20). 
![image](https://github.com/MegaMek/megamek/assets/59574316/b7e17480-04ff-4c16-97fe-614437a45e48)


If you decide to remove the LBXHandler code and leave the adjusted weapon AVs (a perfectly reasonable choice), also fix the [Silver Bullet Gauss Rifle](https://github.com/MegaMek/megamek/blob/master/megamek/src/megamek/common/weapons/gaussrifles/ISSilverBulletGauss.java) AV, since it counts as an LBX weapon.

2024-06-13 23:35 UTC, Sleet01 commented
Pretty sure this is the way it is because we have multiple consumers of the AV values, only some of which are actually Aerospace units.  Just changing the AV values won't produce correct behavior in all cases.

2024-06-13 23:39 UTC, Sleet01 commented
> If you decide to remove the LBXHandler code and leave the adjusted weapon AVs (a perfectly reasonable choice), also fix the [Silver Bullet Gauss Rifle](https://github.com/MegaMek/megamek/blob/master/megamek/src/megamek/common/weapons/gaussrifles/ISSilverBulletGauss.java) AV, since it counts as an LBX weapon.

Also note that I changed the SB Gauss AV value _to_ 15 _from_ 9 specifically because of this code.  Which has been in place for 11 years.

Was this PR submitted due to an issue, or just because the values looked wrong?

2024-06-13 23:55 UTC, gsparks3 commented
> Also note that I changed the SB Gauss AV value _to_ 15 _from_ 9 specifically because of this code. Which has been in place for 11 years.
That must have been where I remembered it from, I was looking for the issue report or change history for a LBX change and couldn't find anything, heh.

2024-06-15 08:45 UTC, Sleet01 requested changes
I'd like us to hold off on this unless it also includes updating the LBX handler that already lowers the AV value, as well as any other weapons currently affected by it (such as the Silver Bullet Gauss).
It may be that we no longer need to have both a full and an Aero-specific AV value, but I don't think that question has been answered satisfactorily yet.

2024-09-04 20:03 UTC, SJuliez commented
It feels like we can close this, right?

2024-09-04 20:10 UTC, IllianiCBT commented
I opted to withhold the review requested from me, as I don't know enough about the rules to make a reliable judgement call. Also, this was before I opted to avoid reviewing MM content too much due to my unfamiliarity with the codebase.

2024-09-21 07:36 UTC, SJuliez commented
Closing this as per the above comments (seems unnecessary or at least, it would require the LBX handler to be updated)

2024-09-21 07:36 UTC, closed without merging